package com.purchasingpower.autoflow.workflow.agents;

import com.purchasingpower.autoflow.service.BitbucketService;
import com.purchasingpower.autoflow.service.GitOperationsService;
import com.purchasingpower.autoflow.workflow.state.*;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * AGENT 10: PR Creator
 *
 * Purpose: Create branch, commit, push, create PR
 *
 * REUSES existing services:
 * - GitOperationsService (create branch, commit, push)
 * - BitbucketService (create PR)
 *
 * This is the FINAL agent - workflow ends here!
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class PRCreatorAgent {

    private final GitOperationsService gitService;
    private final BitbucketService bitbucketService;

    public AgentDecision execute(WorkflowState state) {
        log.info("🚀 Creating PR...");

        try {
            // Generate branch name
            String branchName = state.getGeneratedCode().getBranchName();
            if (branchName == null || branchName.isEmpty()) {
                branchName = generateBranchName(state);
            }

            log.info("Creating branch: {}", branchName);

            // Create and checkout branch (reuse existing service!)
            gitService.createAndCheckoutBranch(state.getWorkspaceDir(), branchName);

            // Commit changes (reuse existing service!)
            String commitMessage = generateCommitMessage(state);
            gitService.commitAndPush(state.getWorkspaceDir(), commitMessage);

            log.info("Pushed commits to: {}", branchName);

            // Create PR in Bitbucket (reuse existing service!)
            String repoName = extractRepoName(state.getRepoUrl());
            String baseBranch = state.getBaseBranch() != null ?
                    state.getBaseBranch() : "develop";

            String prUrl = bitbucketService.createPullRequest(
                    repoName,
                    branchName,
                    baseBranch,
                    state.getPrDescription() // Generated by ReadmeGeneratorAgent
            );

            state.setPrUrl(prUrl);

            log.info("✅ PR created: {}", prUrl);

            // SUCCESS! Workflow complete.
            return AgentDecision.endSuccess(
                    "🎉 **PR Created Successfully!**\n\n" +
                            "**Link:** " + prUrl + "\n\n" +
                            "**Next Steps:**\n" +
                            "1. Review the PR\n" +
                            "2. Run CI/CD pipeline\n" +
                            "3. Merge when ready"
            );

        } catch (Exception e) {
            log.error("Failed to create PR", e);
            return AgentDecision.error("PR creation failed: " + e.getMessage());
        }
    }

    private String generateBranchName(WorkflowState state) {
        String taskType = state.getRequirementAnalysis().getTaskType();
        String domain = state.getRequirementAnalysis().getDomain();

        String prefix = switch (taskType.toLowerCase()) {
            case "bug_fix" -> "fix";
            case "feature" -> "feat";
            case "refactor" -> "refactor";
            case "test" -> "test";
            default -> "chore";
        };

        // Sanitize requirement for branch name
        String sanitized = state.getRequirement()
                .toLowerCase()
                .replaceAll("[^a-z0-9]+", "-")
                .substring(0, Math.min(50, state.getRequirement().length()));

        return String.format("%s/%s-%s", prefix, domain, sanitized);
    }

    private String generateCommitMessage(WorkflowState state) {
        String taskType = state.getRequirementAnalysis().getTaskType();
        String summary = state.getRequirementAnalysis().getSummary();

        StringBuilder msg = new StringBuilder();

        // Conventional commit format
        msg.append(taskType.replace("_", " ")).append(": ");
        msg.append(summary);
        msg.append("\n\n");

        // Add details
        if (state.getLogAnalysis() != null) {
            msg.append("Root Cause: ")
                    .append(state.getLogAnalysis().getRootCauseHypothesis())
                    .append("\n");
        }

        msg.append("\nFiles changed:\n");
        state.getGeneratedCode().getEdits().forEach(edit ->
                msg.append("- ").append(edit.getPath()).append("\n")
        );

        msg.append("\nGenerated by AutoFlow AI");

        return msg.toString();
    }

    private String extractRepoName(String repoUrl) {
        String[] parts = repoUrl.replace(".git", "").split("/");
        return parts[parts.length - 1];
    }
}