package com.purchasingpower.autoflow.workflow.pipeline;

import com.purchasingpower.autoflow.model.jira.JiraIssueDetails;
import com.purchasingpower.autoflow.model.llm.CodeGenerationResponse;
import lombok.Data;
import lombok.RequiredArgsConstructor;

import java.io.File;

@Data
@RequiredArgsConstructor
public class PipelineContext {

    // --- INPUT ---
    private final String issueKey;

    // --- STEP 1: JIRA DATA ---
    private JiraIssueDetails jiraIssue;
    private String repoUrl;      // Extracted from dynamic Jira field
    private String repoName;     // Extracted from dynamic Jira field
    private String baseBranch;   // e.g., "feat/PROJ-123"
    private String requirements;

    // --- STEP 2: GIT WORKSPACE ---
    private File workspaceDir;   // The local folder where we cloned code

    // --- STEP 3: RAG & AI ---
    private String pineconeContext;        // Relevant code snippets found in Vector DB
    private CodeGenerationResponse llmPlan; // The JSON edits generated by Gemini

    private String targetBranch;
    // --- STEP 6: OUTPUT ---
    private String prUrl;        // The final Bitbucket PR link
}